[package]
name = "SCLP"
version = "1.1.3"
edition = "2024"
description = "Simple Command Line Parser Built with Rust."
authors = ["CipherDay"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/CipherDay/SCLP"

[dependencies]
